# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GitFinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation
from PyQt5.QtWidgets import QGraphicsOpacityEffect

from LinkedListfile import LinkedList

global number, numberOfCurrentC, linkedLists, switch, times, tableitems, help_log, namayesh
number = 1
numberOfCurrentC = 0
linkedLists = [LinkedList("main", "c0")]
switch = [["c0", False]]
times = []
tableitems = []
help_log = False


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(QtCore.QRect(350, 50, 1277, 949))
        MainWindow.setStyleSheet("                                        background-color: #5cbcfc; \n")
        # MainWindow.resize(1277, 949)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.opacity_effect1 = QGraphicsOpacityEffect()
        self.opacity_effect2 = QGraphicsOpacityEffect()
        self.opacity_effect3 = QGraphicsOpacityEffect()
        self.opacity_effect4 = QGraphicsOpacityEffect()
        self.opacity_effect1.setOpacity(0)
        self.opacity_effect2.setOpacity(0)
        self.opacity_effect3.setOpacity(0)
        self.opacity_effect4.setOpacity(0)

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(840, 20, 421, 731))
        self.listWidget.setStyleSheet("                                        border: 2px solid #536162;\n"
                                      "                                        color: black;\n"
                                      "                                        text-align: center;\n"
                                      "                                        text-decoration: none;\n"
                                      "                                        display: inline-block;\n"
                                      "                                        font-size: 25px;\n"
                                      "                                        border-radius: 10px;\n"
                                      "                                        padding: 20px\n"
                                      "")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setVisible(False)

        self.input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_1.setGeometry(QtCore.QRect(70, 820, 1141, 71))
        self.input_1.setStyleSheet("                                        background-color: #536162; \n"
                                   "                                        border: none;\n"
                                   "                                        color: white;\n"
                                   "                                        text-align: center;\n"
                                   "                                        text-decoration: none;\n"
                                   "                                        display: inline-block;\n"
                                   "                                        font-size: 30px;\n"
                                   "                                        border-radius: 20px;\n"
                                   "                                        color: #F3F4ED;\n"
                                   "padding:10px")
        self.input_1.setObjectName("input_1")
        self.input_1.editingFinished.connect(self.entered)

        self.khatOfoghi = QtWidgets.QFrame(self.centralwidget)
        self.khatOfoghi.setGeometry(QtCore.QRect(10, 770, 1261, 20))
        self.khatOfoghi.setStyleSheet("color: rgb(65, 65, 65);")
        self.khatOfoghi.setFrameShadow(QtWidgets.QFrame.Plain)
        self.khatOfoghi.setLineWidth(4)
        self.khatOfoghi.setMidLineWidth(0)
        self.khatOfoghi.setFrameShape(QtWidgets.QFrame.HLine)
        self.khatOfoghi.setObjectName("khatOfoghi")

        self.c0 = QtWidgets.QLabel(self.centralwidget)
        self.c0.setGeometry(QtCore.QRect(30, 30, 61, 61))
        self.c0.setStyleSheet("                                        background-color: rgb(255, 102, 211); \n"
                              "                                        border: 3px solid white;\n"
                              "                                        color: black;\n"
                              "                                        text-align: center;\n"
                              "                                        text-decoration: none;\n"
                              "                                        display: inline-block;\n"
                              "                                        font-size: 20px;\n"
                              "                                        border-radius: 30px;\n"
                              "                                       ")
        self.c0.setAlignment(QtCore.Qt.AlignCenter)
        self.c0.setObjectName("c0")

        self.head = QtWidgets.QLabel(self.centralwidget)
        self.head.setGeometry(QtCore.QRect(70, 20, 61, 31))
        self.head.setStyleSheet("                                        background-color: rgb(114, 120, 255); \n"
                                "                                        border: none;\n"
                                "                                        color: black;\n"
                                "                                        text-align: center;\n"
                                "                                        text-decoration: none;\n"
                                "                                        display: inline-block;\n"
                                "                                        font-size: 20px;\n"
                                "                                        border-radius: 10px;\n"
                                "                                        z-index: 5;\n"
                                "")
        self.head.setAlignment(QtCore.Qt.AlignCenter)
        self.head.setObjectName("head")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1277, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_1.setText(_translate("MainWindow", "~ Desktop\LinkedList\Git    (main)     $  "))
        self.c0.setText(_translate("MainWindow", "c0"))
        self.head.setText(_translate("MainWindow", "head"))

    def entered(self):
        global number, namayesh, linkedLists, numberOfCurrentC, switch, times, tableitems, help_log
        namayesh = True
        if help_log:
            self.opacity_effect4.setOpacity(1)
            self.animation4 = QPropertyAnimation(self.opacity_effect4, b"opacity")
            self.animation4.setStartValue(1)
            self.animation4.setEndValue(0)
            self.animation4.setDuration(800)
            self.animation4.start()
            help_log = False

        vorodi = self.input_1.text()
        if "    $  git commit" in vorodi:

            ct = datetime.now()
            date_time = ct.strftime("  %H:%M:%S    %Y/%d/%m")
            times.append([{"name": "c%s" % number, "timestamp": ct.timestamp(), "date": date_time}])

            linkedLists[-1].insert_at_end("c%s" % number)
            self.creat_label_line("commit")
            numberOfCurrentC = number
            number += 1
            tableitems.clear()
            for itemm in times:
                cel = ""
                cel += "  " + itemm[0]["name"] + "   " + itemm[0]["date"]
                tableitems.append(cel)

        elif "    $  git switch " in vorodi:
            for item in linkedLists:
                if item.search_at_value(vorodi.split(" ")[14]):
                    linkedLists.append(LinkedList("main", vorodi.split(" ")[14]))

                    numberOfCurrentC = int(vorodi.split(" ")[14][1:])
                    switch.append([vorodi.split(" ")[14], True])
                    self.head.hide()
                    self.head = QtWidgets.QLabel(self.centralwidget)
                    self.head.setGeometry(
                        QtCore.QRect(self.__dict__[vorodi.split(" ")[14]].x() + 40,
                                     self.__dict__[vorodi.split(" ")[14]].y() - 10, 61,
                                     31))
                    self.head.setStyleSheet(
                        "                                        background-color: rgb(114, 120, 255); \n"
                        "                                        border: none;\n"
                        "                                        color: black;\n"
                        "                                        text-align: center;\n"
                        "                                        text-decoration: none;\n"
                        "                                        display: inline-block;\n"
                        "                                        font-size: 20px;\n"
                        "                                        border-radius: 10px;\n"
                        "                                        z-index: 5;\n"
                        "")
                    self.head.setAlignment(QtCore.Qt.AlignCenter)
                    self.head.setObjectName("head")
                    self.head.setText(QtCore.QCoreApplication.translate("MainWindow", "head"))
                    self.head.show()
                    self.head.setGraphicsEffect(self.opacity_effect3)
                    self.animation3 = QPropertyAnimation(self.opacity_effect3, b"opacity")
                    self.animation3.setStartValue(0)
                    self.animation3.setEndValue(1)
                    self.animation3.setDuration(1000)
                    self.animation3.start()
                    break

        elif "    $  git log" in vorodi:
            namayesh = False
            help_log = True
            self.listWidget.setVisible(True)
            self.listWidget.setGraphicsEffect(self.opacity_effect4)
            self.animation3 = QPropertyAnimation(self.opacity_effect4, b"opacity")
            self.animation3.setStartValue(0)
            self.animation3.setEndValue(1)
            self.animation3.setDuration(800)
            self.animation3.start()
            self.listWidget.clear()
            self.listWidget.addItems(tableitems)

        else:
            namayesh = False

        if namayesh:
            print("~ Desktop\LinkedList\Git    (main)")
            for item in linkedLists:
                item.print()
            print()
            for item in tableitems:
                print(item)
            print()
            print(F"numberOfCurrentC : {numberOfCurrentC}")
            print("\n----------------")
            print("----------------\n")
            namayesh = True

        self.input_1.setText(
            QtCore.QCoreApplication.translate("MainWindow", "~ Desktop\LinkedList\Git    (main)     $  "))

    def creat_label_line(self, noe):
        global number, linkedLists, numberOfCurrentC, switch

        if not switch[-1][1]:
            frameshape_help = QtWidgets.QFrame.VLine
            x1_help, x2_help = 20, 0
            y1_help, y2_help = 60, 120
            w1_help, w2_help = 20, 61
            h1_help, h2_help = 61, 61
        else:
            switch[-1][1] = False
            frameshape_help = QtWidgets.QFrame.HLine
            x1_help, x2_help = 60, 120
            y1_help, y2_help = 20, 0
            w1_help, w2_help = 61, 61
            h1_help, h2_help = 20, 61
        if noe == "commit":
            self.__dict__["line_%s" % number] = QtWidgets.QFrame(self.centralwidget)
            self.__dict__["line_%s" % number].setGeometry(
                QtCore.QRect(self.__dict__["c%s" % numberOfCurrentC].x() + x1_help,
                             self.__dict__["c%s" % numberOfCurrentC].y() + y1_help,
                             w1_help, h1_help))
            self.__dict__["line_%s" % number].setFrameShadow(QtWidgets.QFrame.Plain)
            self.__dict__["line_%s" % number].setLineWidth(3)
            self.__dict__["line_%s" % number].setFrameShape(frameshape_help)
            self.__dict__["line_%s" % number].setObjectName("line_%s" % numberOfCurrentC)
            self.__dict__["line_%s" % number].setGraphicsEffect(self.opacity_effect1)
            self.__dict__["line_%s" % number].show()

            self.animation = QPropertyAnimation(self.opacity_effect1, b"opacity")
            self.animation.setStartValue(0)
            self.animation.setEndValue(1)
            self.animation.setDuration(700)
            self.animation.start()

            self.__dict__["c%s" % number] = QtWidgets.QLabel(self.centralwidget)
            self.__dict__["c%s" % number].setGeometry(
                QtCore.QRect(self.__dict__["c%s" % numberOfCurrentC].x() + x2_help,
                             self.__dict__["c%s" % numberOfCurrentC].y() + y2_help, w2_help,
                             h2_help))
            self.__dict__["c%s" % number].setStyleSheet(
                f"                                        background-color: rgb(255, 102, 211); \n"
                "                                        border: 3px solid white;\n"
                "                                        color: black;\n"
                "                                        text-align: center;\n"
                "                                        text-decoration: none;\n"
                "                                        display: inline-block;\n"
                "                                        font-size: 20px;\n"
                "                                        border-radius: 30px;\n"
                "                                       ")
            self.__dict__["c%s" % number].setAlignment(QtCore.Qt.AlignCenter)
            self.__dict__["c%s" % number].setObjectName("c%s" % number)
            self.__dict__["c%s" % number].setText(
                QtCore.QCoreApplication.translate("MainWindow", "c%s" % number))
            self.__dict__["c%s" % number].setGraphicsEffect(self.opacity_effect2)
            self.__dict__["c%s" % number].show()

            self.animation2 = QPropertyAnimation(self.opacity_effect2, b"opacity")
            self.animation2.setStartValue(0)
            self.animation2.setEndValue(1)
            self.animation2.setDuration(700)
            self.animation2.start()

            self.head.hide()
            self.head = QtWidgets.QLabel(self.centralwidget)
            self.head.setGeometry(
                QtCore.QRect(self.__dict__["c%s" % number].x() + 40, self.__dict__["c%s" % number].y() - 10, 61, 31))
            self.head.setStyleSheet("                                        background-color: rgb(114, 120, 255); \n"
                                    "                                        border: none;\n"
                                    "                                        color: black;\n"
                                    "                                        text-align: center;\n"
                                    "                                        text-decoration: none;\n"
                                    "                                        display: inline-block;\n"
                                    "                                        font-size: 20px;\n"
                                    "                                        border-radius: 10px;\n"
                                    "                                        z-index: 5;\n"
                                    "")
            self.head.setAlignment(QtCore.Qt.AlignCenter)
            self.head.setObjectName("head")
            self.head.setText(QtCore.QCoreApplication.translate("MainWindow", "head"))
            self.head.show()
            self.head.setGraphicsEffect(self.opacity_effect3)
            self.animation3 = QPropertyAnimation(self.opacity_effect3, b"opacity")
            self.animation3.setStartValue(0)
            self.animation3.setEndValue(1)
            self.animation3.setDuration(1000)
            self.animation3.start()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QStackedWidget()
    widget.setGeometry(QtCore.QRect(350, 50, 1277, 949))
    widget.setWindowTitle("Git Bash")
    widget.setWindowIcon(QtGui.QIcon('github.png'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    widget.addWidget(MainWindow)
    widget.show()
    sys.exit(app.exec_())
